[package]
name = "dwarf-to-struct"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"
clap = {version="*", features=["derive"]}
itertools = "*"

gimli = "0.31.0"
object = "0.36.0"
fallible-iterator = "*"
